from app import safe_translate as _

devices_types = {
    "camera": _("Video camera, video intercom, door peephole with camera"),
    "cooking": _("Refrigerator, oven"),
    "cooking.coffee_maker": _("Coffee maker, coffee machine"),
    "cooking.kettle": _("Smart kettle, thermal pot"),
    "cooking.multicooker": _("Multicooker"),
    "dishwasher": _("Dishwasher"),
    "humidifier": _("Air humidifier"),
    "iron": _("Iron, steam generator"),
    "light": _("Light bulb, lamp, night light"),
    "light.ceiling": _("Chandelier"),
    "light.strip": _("LED strip"),
    "media_device": _("DVD player and other media devices"),
    "media_device.receiver": _("Satellite receiver, IR remote for receiver, AV receiver"),
    "media_device.tv": _("Smart TV, IR remote for TV, media set-top box, receiver"),
    "media_device.tv_box": _("Smart TV box, IR remote for TV box"),
    "openable": _("Door, gate, window, shutters"),
    "openable.curtain": _("Curtains, blinds"),
    "openable.valve": _("Ball valve"),
    "other": _("Other devices"),
    "pet_drinking_fountain": _("Pet water fountain"),
    "pet_feeder": _("Pet feeder"),
    "purifier": _("Air purifier, air washer"),
    "sensor": _("Motion sensor, humidity sensor and other sensors"),
    "sensor.button": _("Smart button"),
    "sensor.climate": _("Climate sensor"),
    "sensor.gas": _("Gas sensor"),
    "sensor.illumination": _("Light sensor"),
    "sensor.motion": _("Motion sensor"),
    "sensor.open": _("Door sensor"),
    "sensor.smoke": _("Smoke sensor"),
    "sensor.vibration": _("Vibration sensor"),
    "sensor.water_leak": _("Water leak sensor"),
    "smart_meter": _("Meter"),
    "smart_meter.cold_water": _("Cold water meter"),
    "smart_meter.electricity": _("Electricity meter"),
    "smart_meter.gas": _("Gas meter"),
    "smart_meter.heat": _("Heat meter"),
    "smart_meter.hot_water": _("Hot water meter"),
    "socket": _("Smart socket"),
    "switch": _("Switch"),
    "thermostat": _("Water heater, underfloor heating, heater, electric fan"),
    "thermostat.ac": _("Air conditioner"),
    "vacuum_cleaner": _("Robot vacuum"),
    "ventilation": _("Breezer, hood, supply ventilation system"),
    "ventilation.fan": _("Fan"),
    "washing_machine": _("Washing machine"),
}

devices_instance = {
    "controls_locked": {
        "instance_name": "controls_locked",
        "description": _("Control lock"),
        "capability": "toggle",
        "default_value": False,
    },
    "on": {
        "instance_name": "on",
        "description": _("Turn on/off"),
        "capability": "on_off",
        "default_value": 0,
        "parameters": {
            "split": False,
        },
    },
    "humidity": {
        "instance_name": "humidity",
        "description": _("Humidity"),
        "capability": "range",
        "default_value": 0,
        "parameters": {
            "unit": "unit.percent",
            "range": {"min": 0, "max": 100, "precision": 5},
        },
    },
    "volume": {
        "instance_name": "volume",
        "description": _("Volume"),
        "capability": "range",
        "default_value": 1,
        "parameters": {"range": {"min": 1, "max": 100, "precision": 1}},
    },
    "input_source": {
        "instance_name": "input_source",
        "description": _("Signal source"),
        "capability": "mode",
        "default_value": "one",
        "parameters": {
            "modes": [
                {"value": "one"},
                {"value": "two"},
                {"value": "three"},
                {"value": "four"},
                {"value": "five"},
                {"value": "six"},
                {"value": "seven"},
                {"value": "eight"},
                {"value": "nine"},
                {"value": "ten"},
            ],
            "ordered": False,
        },
    },
    "program": {
        "instance_name": "program",
        "description": _("Operation programs"),
        "capability": "mode",
        "default_value": "one",
        "parameters": {
            "modes": [
                {"value": "auto"},
                {"value": "express"},
                {"value": "one"},
                {"value": "two"},
                {"value": "three"},
                {"value": "four"},
                {"value": "five"},
                {"value": "six"},
                {"value": "seven"},
                {"value": "eight"},
                {"value": "nine"},
                {"value": "ten"},
            ],
            "ordered": False,
        },
    },
    "pause": {
        "instance_name": "pause",
        "description": _("Pause"),
        "capability": "toggle",
        "default_value": False,
    },
    "backlight": {
        "instance_name": "backlight",
        "description": _("Backlight"),
        "capability": "toggle",
        "default_value": False,
    },
    "mute": {
        "instance_name": "mute",
        "description": _("Mute mode"),
        "capability": "toggle",
        "default_value": False,
    },
    "oscillation": {
        "instance_name": "oscillation",
        "description": _("Rotation mode"),
        "capability": "toggle",
        "default_value": False,
    },
    "ionization": {
        "instance_name": "ionization",
        "description": _("Ionization mode"),
        "capability": "toggle",
        "default_value": False,
    },
    "keep_warm": {
        "instance_name": "keep_warm",
        "description": _("Keep warm mode"),
        "capability": "toggle",
        "default_value": False,
    },
    "fan_speed": {
        "instance_name": "fan_speed",
        "description": _("Ventilation speed"),
        "capability": "mode",
        "parameters": {
            "modes": [
                {"value": "auto"},
                {"value": "low"},
                {"value": "medium"},
                {"value": "high"},
            ],
            "ordered": True,
        },
    },
    "open": {
        "instance_name": "open",
        "description": _("Opening degree"),
        "capability": "range",
        "default_value": 0,
        "parameters": {
            "unit": "unit.percent",
            "range": {"min": 0, "max": 100, "precision": 10},
        },
    },
    "channel": {
        "instance_name": "channel",
        "description": _("TV channel"),
        "capability": "range",
        "default_value": 1,
        "parameters": {"range": {"min": 0, "max": 999, "precision": 1}},
    },
    "temperature": {
        "instance_name": "temperature",
        "description": _("Temperature"),
        "capability": "range",
        "default_value": 20,
        "parameters": {
            "unit": "unit.temperature.celsius",
            "range": {"min": 1, "max": 100, "precision": 1},
        },
    },
    "cleanup_mode": {
        "instance_name": "cleanup_mode",
        "description": _("Cleaning mode"),
        "capability": "mode",
        "parameters": {
            "modes": [
                {"value": "auto"},
                {"value": "eco"},
                {"value": "express"},
                {"value": "normal"},
                {"value": "quiet"},
                {"value": "wet_cleaning"},
                {"value": "dry_cleaning"},
                {"value": "mixed_cleaning"},
            ],
            "ordered": True,
        },
    },
    "thermostat": {
        "instance_name": "thermostat",
        "description": _("Temperature mode"),
        "capability": "mode",
        "parameters": {
            "modes": [
                {"value": "auto"},
                {"value": "heat"},
                {"value": "cool"},
                {"value": "eco"},
                {"value": "dry"},
                {"value": "fan_only"},
                {"value": "turbo"},
            ],
            "ordered": True,
        },
    },
    "work_speed": {
        "instance_name": "work_speed",
        "description": _("Operation speed"),
        "capability": "mode",
        "parameters": {
            "modes": [
                {"value": "auto"},
                {"value": "fast"},
                {"value": "max"},
                {"value": "medium"},
                {"value": "min"},
                {"value": "slow"},
                {"value": "turbo"},
            ],
            "ordered": True,
        },
    },
    "temperature_k": {
        "instance_name": "temperature_k",
        "description": _("Color temperature"),
        "capability": "color_setting",
        "default_value": 4500,
        "parameters": {"temperature_k": {"min": 2700, "max": 9000, "precision": 1}},
    },
    "rgb": {
        "instance_name": "rgb",
        "description": _("Color in RGB format"),
        "capability": "color_setting",
        "default_value": "000000",
        "parameters": {"color_model": "rgb"},
    },
    "brightness": {
        "instance_name": "brightness",
        "description": _("Brightness"),
        "capability": "range",
        "default_value": 50,
        "parameters": {
            "unit": "unit.percent",
            "range": {"min": 1, "max": 100, "precision": 1},
        },
    },
    "color_scene": {
        "instance_name": "color_scene",
        "description": _("Operation mode of lighting elements"),
        "capability": "color_setting",
        "default_value": 4500,
        "parameters": {
            "color_scene": {
                "scenes": [
                    {"id": "alarm"},
                    {"id": "alice"},
                    {"id": "candle"},
                    {"id": "dinner"},
                    {"id": "fantasy"},
                    {"id": "garland"},
                    {"id": "jungle"},
                    {"id": "movie"},
                    {"id": "night"},
                    {"id": "neon"},
                    {"id": "ocean"},
                    {"id": "party"},
                    {"id": "rest"},
                    {"id": "romance"},
                    {"id": "siren"},
                ]
            }
        },
    },
    # float sensors
    "amperage_sensor": {
        "instance_name": "amperage_sensor",
        "description": _("Current"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.ampere"},
    },
    "battery_level_sensor": {
        "instance_name": "battery_level_sensor",
        "description": _("Battery level"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.percent"},
    },
    "co2_level_sensor": {
        "instance_name": "co2_level_sensor",
        "description": _("Carbon dioxide"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.ppm"},
    },
    "humidity_sensor": {
        "instance_name": "humidity_sensor",
        "description": _("Humidity"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.percent"},
    },
    "illumination_sensor": {
        "instance_name": "illumination_sensor",
        "description": _("Illumination"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.illumination.lux"},
    },
    "pm1_density_sensor": {
        "instance_name": "pm1_density_sensor",
        "description": _("Air pollution with PM1 particles"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.density.mcg_m3"},
    },
    "pm2.5_density_sensor": {
        "instance_name": "pm2.5_density_sensor",
        "description": _("Air pollution with PM2.5 particles"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.density.mcg_m3"},
    },
    "pm10_density_sensor": {
        "instance_name": "pm10_density_sensor",
        "description": _("Air pollution with PM10 particles"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.density.mcg_m3"},
    },
    "power_sensor": {
        "instance_name": "power_sensor",
        "description": _("Power"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.watt"},
    },
    "food_level": {
        "instance_name": "food_level",
        "description": _("Display of feed level readings"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.percent "},
    },
    "meter_sensor": {
        "instance_name": "meter_sensor",
        "description": _("Universal meter readings"),
        "capability": "float",
        "default_value": 0,
    },
    "electricity_meter_sensor": {
        "instance_name": "electricity_meter_sensor",
        "description": _("Electricity readings"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.kilowatt_hour"},
    },
    "water_meter_sensor": {
        "instance_name": "water_meter_sensor",
        "description": _("Water readings"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.cubic_meter"},
    },
    "gas_meter_sensor": {
        "instance_name": "gas_meter_sensor",
        "description": _("Gas readings"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.cubic_meter"},
    },
    "heat_meter_sensor": {
        "instance_name": "heat_meter_sensor",
        "description": _("Heat readings"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.gigacalorie"},
    },
    "pressure_sensor": {
        "instance_name": "pressure_sensor",
        "description": _("Pressure mmHg"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.pressure.mmhg"},
    },
    "temperature_sensor": {
        "instance_name": "temperature_sensor",
        "description": _("Temperature"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.temperature.celsius"},
    },
    "tvoc_sensor": {
        "instance_name": "tvoc_sensor",
        "description": _("Air pollution with organic substances"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.density.mcg_m3"},
    },
    "voltage_sensor": {
        "instance_name": "voltage_sensor",
        "description": _("Voltage"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.volt"},
    },
    "water_level_sensor": {
        "instance_name": "water_level_sensor",
        "description": _("Water level"),
        "capability": "float",
        "default_value": 0,
        "parameters": {"unit": "unit.percent"},
    },
    # event sensors
    "vibration_event": {
        "instance_name": "vibration_event",
        "description": _("Vibration/fall/tilt sensor"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "tilt"},
                {"value": "fall"},
            ]
        },
    },
    "open_event": {
        "instance_name": "open_event",
        "description": _("Open/close sensor"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "opened"},
                {"value": "closed"},
            ]
        },
    },
    "button_event": {
        "instance_name": "button_event",
        "description": _("Button press event"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "click"},
                {"value": "double_click"},
                {"value": "long_press"},
            ]
        },
    },
    "motion_event": {
        "instance_name": "motion_event",
        "description": _("Motion sensor"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "detected"},
                {"value": "not_detected"},
            ]
        },
    },
    "smoke_event": {
        "instance_name": "smoke_event",
        "description": _("Smoke sensor"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "detected"},
                {"value": "not_detected"},
                {"value": "high"},
            ]
        },
    },
    "gas_event": {
        "instance_name": "gas_event",
        "description": _("Gas presence sensor in the room"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "detected"},
                {"value": "not_detected"},
                {"value": "high"},
            ]
        },
    },
    "battery_level_event": {
        "instance_name": "battery_level_event",
        "description": _("Battery charge"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "low "},
                {"value": "normal"},
            ]
        },
    },
    "food_level_event": {
        "instance_name": "food_level_event",
        "description": _("Feed level"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "empty"},
                {"value": "low"},
                {"value": "normal"},
            ]
        },
    },
    "water_level_event": {
        "instance_name": "water_level_event",
        "description": _("Water level"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "empty"},
                {"value": "low"},
                {"value": "normal"},
            ]
        },
    },
    "water_leak_event": {
        "instance_name": "water_leak_event",
        "description": _("Leak sensor"),
        "capability": "event",
        "default_value": 0,
        "parameters": {
            "events": [
                {"value": "dry"},
                {"value": "leak"},
            ]
        },
    },
}
